name: datid3d
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=9.3.0
  - scipy=1.7.1
  - cudatoolkit=11.6
  - cudnn=8.3.2
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - torchvision=0.13.1
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - x264
  - ffmpeg=4.3.2
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - tensorflow==2.11.0
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - transformers
    - diffusers[torch]
    - face_alignment
    - mtcnn
    - kornia
    - dominate
    - gdown
    - trimesh
    - gradio
