name: datid3d
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow=9.3.0
  - scipy=1.7.1
  - pytorch=1.13.0
  - torchvision=0.14.0
  - cudatoolkit=11.6
  - requests=2.26.0
  - tqdm=4.62.2
  - ninja=1.10.2
  - matplotlib=3.4.2
  - imageio=2.9.0
  - pip:
    - imgui==1.3.0
    - glfw==2.2.0
    - pyopengl==3.1.5
    - imageio-ffmpeg==0.4.3
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - transformers
    - diffusers[torch]
    - face_alignment
    - mtcnn
    - tensorflow
    - kornia
    - dominate
    - gdown
    - trimesh
